// Committed offline fallback for /teams/:teamId/drivers/:driverId —
// consumed by src/lib/api/jolpica.ts (getDriverSeasonResults).
// Keyed by OUR driver slug (see src/data/idMaps.ts).
// GENERATED by scripts/refresh-data.ts (`npm run data:refresh`) — do not
// hand-edit. Snapshot of live Jolpica data.
import type { DriverSeasonResult } from '../../types';

export const driverResultsSnapshot: {
  fetchedAt: string;
  results: Record<string, DriverSeasonResult[]>;
} = {
  fetchedAt: '2026-06-12',
  results: {
    "george-russell": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 1,
        "points": 25,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 2,
        "points": 18,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 4,
        "points": 12,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 4,
        "points": 12,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 12,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "kimi-antonelli": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 2,
        "points": 18,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 1,
        "points": 25,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 1,
        "points": 25,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 1,
        "points": 25,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 1,
        "points": 25,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 1,
        "points": 25,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "charles-leclerc": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 3,
        "points": 15,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 4,
        "points": 12,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 3,
        "points": 15,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 8,
        "points": 4,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 4,
        "points": 12,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      }
    ],
    "lewis-hamilton": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 4,
        "points": 12,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 3,
        "points": 15,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 6,
        "points": 8,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 6,
        "points": 8,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 2,
        "points": 18,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 2,
        "points": 18,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "lando-norris": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 5,
        "points": 10,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Did not start"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 5,
        "points": 10,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 2,
        "points": 18,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      }
    ],
    "max-verstappen": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 6,
        "points": 8,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 8,
        "points": 4,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 5,
        "points": 10,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 3,
        "points": 15,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      }
    ],
    "oliver-bearman": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 7,
        "points": 6,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 5,
        "points": 10,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 11,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 10,
        "points": 1,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      }
    ],
    "arvid-lindblad": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 8,
        "points": 4,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 12,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 14,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 14,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Did not start"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 6,
        "points": 8,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "gabriel-bortoleto": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 9,
        "points": 2,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Did not start"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 13,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 12,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 13,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 11,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "pierre-gasly": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 10,
        "points": 1,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 6,
        "points": 8,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 7,
        "points": 6,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 8,
        "points": 4,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 7,
        "points": 6,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "esteban-ocon": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 11,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 14,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 10,
        "points": 1,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 13,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 14,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 9,
        "points": 2,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "alexander-albon": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 12,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Did not start"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 20,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 10,
        "points": 1,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 8,
        "points": 4,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "liam-lawson": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 13,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 7,
        "points": 6,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 9,
        "points": 2,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 7,
        "points": 6,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 5,
        "points": 10,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "franco-colapinto": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 14,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 10,
        "points": 1,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 16,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 7,
        "points": 6,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 6,
        "points": 8,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 14,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "carlos-sainz": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 15,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 9,
        "points": 2,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 15,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 9,
        "points": 2,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 9,
        "points": 2,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 16,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      }
    ],
    "sergio-perez": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": 16,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 15,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 17,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 16,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 15,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "lance-stroll": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 17,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 15,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      }
    ],
    "fernando-alonso": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 18,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 15,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 10,
        "points": 1,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "valtteri-bottas": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 13,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 19,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 18,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 16,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      }
    ],
    "isack-hadjar": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 8,
        "points": 4,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 12,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 5,
        "points": 10,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 3,
        "points": 15,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "oscar-piastri": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Did not start"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Did not start"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 2,
        "points": 18,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": 3,
        "points": 15,
        "podium": true,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 11,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 4,
        "points": 12,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ],
    "nico-hulkenberg": [
      {
        "round": 1,
        "raceName": "Australian Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Did not start"
      },
      {
        "round": 2,
        "raceName": "Chinese Grand Prix",
        "position": 11,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 3,
        "raceName": "Japanese Grand Prix",
        "position": 11,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      },
      {
        "round": 4,
        "raceName": "Miami Grand Prix",
        "position": null,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Retired"
      },
      {
        "round": 5,
        "raceName": "Canadian Grand Prix",
        "position": 12,
        "points": 0,
        "podium": false,
        "dnf": true,
        "status": "Lapped"
      },
      {
        "round": 6,
        "raceName": "Monaco Grand Prix",
        "position": 13,
        "points": 0,
        "podium": false,
        "dnf": false,
        "status": "Finished"
      }
    ]
  },
};

export const fallbackDriverResults: Record<string, DriverSeasonResult[]> =
  driverResultsSnapshot.results;
