// Committed offline fallback for /standings — consumed by
// src/lib/api/jolpica.ts (getConstructorStandings / getDriverStandings).
// GENERATED by scripts/refresh-data.ts (`npm run data:refresh`) — do not
// hand-edit. Snapshot of live Jolpica data.
import type { ConstructorStanding, DriverStanding } from '../../types';

export const standingsSnapshot: {
  fetchedAt: string;
  constructors: ConstructorStanding[];
  drivers: DriverStanding[];
} = {
  fetchedAt: '2026-06-12',
  constructors: [
    {
      "position": 1,
      "teamId": "mercedes",
      "teamName": "Mercedes",
      "points": 244,
      "wins": 6
    },
    {
      "position": 2,
      "teamId": "ferrari",
      "teamName": "Ferrari",
      "points": 165,
      "wins": 0
    },
    {
      "position": 3,
      "teamId": "mclaren",
      "teamName": "McLaren",
      "points": 118,
      "wins": 0
    },
    {
      "position": 4,
      "teamId": "red-bull",
      "teamName": "Red Bull",
      "points": 72,
      "wins": 0
    },
    {
      "position": 5,
      "teamId": "alpine",
      "teamName": "Alpine F1 Team",
      "points": 41,
      "wins": 0
    },
    {
      "position": 6,
      "teamId": "racing-bulls",
      "teamName": "RB F1 Team",
      "points": 39,
      "wins": 0
    },
    {
      "position": 7,
      "teamId": "haas",
      "teamName": "Haas F1 Team",
      "points": 21,
      "wins": 0
    },
    {
      "position": 8,
      "teamId": "williams",
      "teamName": "Williams",
      "points": 11,
      "wins": 0
    },
    {
      "position": 9,
      "teamId": "audi",
      "teamName": "Audi",
      "points": 2,
      "wins": 0
    },
    {
      "position": 10,
      "teamId": "aston-martin",
      "teamName": "Aston Martin",
      "points": 1,
      "wins": 0
    },
    {
      "position": 11,
      "teamId": "cadillac",
      "teamName": "Cadillac F1 Team",
      "points": 0,
      "wins": 0
    }
  ],
  drivers: [
    {
      "position": 1,
      "driverId": "kimi-antonelli",
      "driverName": "Andrea Kimi Antonelli",
      "teamId": "mercedes",
      "points": 156,
      "wins": 5
    },
    {
      "position": 2,
      "driverId": "lewis-hamilton",
      "driverName": "Lewis Hamilton",
      "teamId": "ferrari",
      "points": 90,
      "wins": 0
    },
    {
      "position": 3,
      "driverId": "george-russell",
      "driverName": "George Russell",
      "teamId": "mercedes",
      "points": 88,
      "wins": 1
    },
    {
      "position": 4,
      "driverId": "charles-leclerc",
      "driverName": "Charles Leclerc",
      "teamId": "ferrari",
      "points": 75,
      "wins": 0
    },
    {
      "position": 5,
      "driverId": "oscar-piastri",
      "driverName": "Oscar Piastri",
      "teamId": "mclaren",
      "points": 60,
      "wins": 0
    },
    {
      "position": 6,
      "driverId": "lando-norris",
      "driverName": "Lando Norris",
      "teamId": "mclaren",
      "points": 58,
      "wins": 0
    },
    {
      "position": 7,
      "driverId": "max-verstappen",
      "driverName": "Max Verstappen",
      "teamId": "red-bull",
      "points": 43,
      "wins": 0
    },
    {
      "position": 8,
      "driverId": "isack-hadjar",
      "driverName": "Isack Hadjar",
      "teamId": "red-bull",
      "points": 29,
      "wins": 0
    },
    {
      "position": 9,
      "driverId": "liam-lawson",
      "driverName": "Liam Lawson",
      "teamId": "racing-bulls",
      "points": 26,
      "wins": 0
    },
    {
      "position": 10,
      "driverId": "pierre-gasly",
      "driverName": "Pierre Gasly",
      "teamId": "alpine",
      "points": 26,
      "wins": 0
    },
    {
      "position": 11,
      "driverId": "oliver-bearman",
      "driverName": "Oliver Bearman",
      "teamId": "haas",
      "points": 18,
      "wins": 0
    },
    {
      "position": 12,
      "driverId": "franco-colapinto",
      "driverName": "Franco Colapinto",
      "teamId": "alpine",
      "points": 15,
      "wins": 0
    },
    {
      "position": 13,
      "driverId": "arvid-lindblad",
      "driverName": "Arvid Lindblad",
      "teamId": "racing-bulls",
      "points": 13,
      "wins": 0
    },
    {
      "position": 14,
      "driverId": "carlos-sainz",
      "driverName": "Carlos Sainz",
      "teamId": "williams",
      "points": 6,
      "wins": 0
    },
    {
      "position": 15,
      "driverId": "alexander-albon",
      "driverName": "Alexander Albon",
      "teamId": "williams",
      "points": 5,
      "wins": 0
    },
    {
      "position": 16,
      "driverId": "esteban-ocon",
      "driverName": "Esteban Ocon",
      "teamId": "haas",
      "points": 3,
      "wins": 0
    },
    {
      "position": 17,
      "driverId": "gabriel-bortoleto",
      "driverName": "Gabriel Bortoleto",
      "teamId": "audi",
      "points": 2,
      "wins": 0
    },
    {
      "position": 18,
      "driverId": "fernando-alonso",
      "driverName": "Fernando Alonso",
      "teamId": "aston-martin",
      "points": 1,
      "wins": 0
    },
    {
      "position": 19,
      "driverId": "nico-hulkenberg",
      "driverName": "Nico Hülkenberg",
      "teamId": "audi",
      "points": 0,
      "wins": 0
    },
    {
      "position": 20,
      "driverId": "valtteri-bottas",
      "driverName": "Valtteri Bottas",
      "teamId": "cadillac",
      "points": 0,
      "wins": 0
    },
    {
      "position": 21,
      "driverId": "sergio-perez",
      "driverName": "Sergio Pérez",
      "teamId": "cadillac",
      "points": 0,
      "wins": 0
    },
    {
      "position": 22,
      "driverId": "lance-stroll",
      "driverName": "Lance Stroll",
      "teamId": "aston-martin",
      "points": 0,
      "wins": 0
    }
  ],
};

export const fallbackConstructorStandings: ConstructorStanding[] = standingsSnapshot.constructors;
export const fallbackDriverStandings: DriverStanding[] = standingsSnapshot.drivers;
