// WorldMap — calendar world stage (PLAN T10, DESIGN §4 dark stage).
// Real Natural Earth 110m coastlines (src/data/worldLand.ts, generated by
// scripts/build-worldmap.mjs) equirectangular-projected into a 1000x500 space.
// `project(lat, lng)` shares that space so markers land on real geography.
// Pure presentational: markers + their interactions are owned by CalendarPage /
// RoundMarker, rendered as `children` in the same SVG coordinate system.
import type { ReactNode } from 'react';
import { motion } from 'framer-motion';
import { DUR, EASE, useReducedMotionSafe } from '../../lib/motion';
import { WORLD_LAND_PATHS } from '../../data/worldLand';

/** Equirectangular projection into the 1000×500 viewBox. */
export function project(lat: number, lng: number): { x: number; y: number } {
  return {
    x: ((lng + 180) / 360) * 1000,
    y: ((90 - lat) / 180) * 500,
  };
}

/** Build an SVG polyline `d` through ordered projected points (the season route). */
function routeD(points: ReadonlyArray<{ x: number; y: number }>): string {
  if (points.length === 0) return '';
  return points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');
}

// Crop the empty Arctic/Antarctic oceans so the inhabited band fills the frame.
const VIEW = { x: 0, y: 28, w: 1000, h: 392 } as const;
const VIEWBOX = `${VIEW.x} ${VIEW.y} ${VIEW.w} ${VIEW.h}`;

// Faint graticule (the "ops-room" world grid). Skip the ±180/±90 edges.
const GRID_LNG = [-150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150];
const GRID_LAT = [60, 30, 0, -30, -60];

export interface WorldMapProps {
  /** Markers/overlays rendered in the same SVG coordinate space. */
  children?: ReactNode;
  /**
   * Ordered projected round coordinates. When provided, a thin connection line
   * is drawn through them (the season "racing line"). The draw-in is animated by
   * the map set piece below. Optional + additive — omit for a static map.
   */
  routePoints?: ReadonlyArray<{ x: number; y: number }>;
  /** Controlled viewBox string for external zoom/pan. Falls back to default crop. */
  viewBox?: string;
  /** Current map zoom scale — used to keep stroke widths constant on screen. */
  scale?: number;
}

export default function WorldMap({ children, routePoints, viewBox: viewBoxProp, scale = 1 }: WorldMapProps) {
  const reduced = useReducedMotionSafe();
  const d = routePoints ? routeD(routePoints) : '';

  // Map set piece (MOTION §3): the land fades up, THEN the route line draws
  // itself in (sequence via delay, never overlap). Reduced motion → instant.
  return (
    <svg
      viewBox={viewBoxProp ?? VIEWBOX}
      className="h-auto w-full"
      role="img"
      aria-label="Bản đồ thế giới với 24 chặng đua mùa giải 2026"
      xmlns="http://www.w3.org/2000/svg"
    >
      <defs>
        <linearGradient id="wm-land" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#262a31" />
          <stop offset="100%" stopColor="#15171c" />
        </linearGradient>
        <linearGradient id="wm-route" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0%" stopColor="#9ca3af" stopOpacity="0.55" />
          <stop offset="50%" stopColor="#e5e7eb" stopOpacity="1" />
          <stop offset="100%" stopColor="#9ca3af" stopOpacity="0.55" />
        </linearGradient>
        <radialGradient id="wm-glow" cx="52%" cy="46%" r="60%">
          <stop offset="0%" stopColor="#3a4150" stopOpacity="0.28" />
          <stop offset="100%" stopColor="#3a4150" stopOpacity="0" />
        </radialGradient>
        {/* Fade the land into the page at the crop edges (no hard coastlines). */}
        <linearGradient id="wm-fade" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#fff" stopOpacity="0" />
          <stop offset="9%" stopColor="#fff" stopOpacity="1" />
          <stop offset="90%" stopColor="#fff" stopOpacity="1" />
          <stop offset="100%" stopColor="#fff" stopOpacity="0" />
        </linearGradient>
        <mask id="wm-edge">
          <rect x={VIEW.x} y={VIEW.y} width={VIEW.w} height={VIEW.h} fill="url(#wm-fade)" />
        </mask>
      </defs>

      {/* Soft depth glow behind the land. */}
      <rect x={VIEW.x} y={VIEW.y} width={VIEW.w} height={VIEW.h} fill="url(#wm-glow)" />

      <g mask="url(#wm-edge)">
        {/* Graticule grid — very faint. */}
        <g stroke="#5b6472" strokeWidth={0.5 / scale} opacity={0.1}>
          {GRID_LNG.map((lng) => {
            const x = project(0, lng).x;
            return <line key={`v${lng}`} x1={x} y1={VIEW.y} x2={x} y2={VIEW.y + VIEW.h} />;
          })}
          {GRID_LAT.map((lat) => {
            const y = project(lat, 0).y;
            return <line key={`h${lat}`} x1={0} y1={y} x2={1000} y2={y} />;
          })}
        </g>

        {/* Real coastlines. */}
        <motion.g
          fill="url(#wm-land)"
          stroke="#3d424b"
          strokeWidth={0.6 / scale}
          strokeOpacity={0.8}
          strokeLinejoin="round"
          fillRule="evenodd"
          initial={reduced ? false : { opacity: 0, y: 10 }}
          animate={reduced ? undefined : { opacity: 1, y: 0 }}
          transition={reduced ? undefined : { duration: DUR.slow, ease: EASE.out }}
        >
          {WORLD_LAND_PATHS.map((p, i) => (
            <path key={i} d={p} />
          ))}
        </motion.g>
      </g>

      {d && (
        <motion.path
          d={d}
          fill="none"
          stroke="url(#wm-route)"
          strokeWidth={2 / scale}
          strokeLinejoin="round"
          strokeLinecap="round"
          aria-hidden="true"
          initial={reduced ? false : { pathLength: 0, opacity: 0 }}
          animate={reduced ? undefined : { pathLength: 1, opacity: 1 }}
          transition={
            reduced
              ? undefined
              : {
                  pathLength: { duration: DUR.set, ease: EASE.move, delay: DUR.slow },
                  opacity: { duration: DUR.fast, delay: DUR.slow },
                }
          }
        />
      )}

      {children}
    </svg>
  );
}
